### ISSUE TITLE
真不错 原版的gulp-asset-rev用不了 希望出点option 比如不用时间错hash10位？console可选？

### ISSUE THREAD

**Issue by lanbosm** [huanghui8030/Gulp#1]

**Comment by huanghui8030** [comment]
没有用hash值主要是考虑到，很多时候文件并不能获取到hash，例如一些公用的插件，例如vue、react、jquery等，大部分时候大家会放到静态服务器上，还有一些夸项目访问的时候，并不在本地。所以才用到每次更新都增加一个时间戳。
